# Generated by Django 5.2.5
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del post', null=True, upload_to='blog_images/'),
        ),
    ]