# Generated by Django 5.2.3 on 2025-08-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_image_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
